version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: awqaf-forms-app
    hostname: awqaf-forms-app
    ports:
      - "80"
    networks:
      - awqaf-forms-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-proxy
    depends_on:
      - app
    ports:
      - "3000:80"  # Expose port 3000 on localhost
    networks:
      - awqaf-forms-network

networks:
  awqaf-forms-network:
    driver: bridge
